In [17]:
import pandas as pd
import numpy as np
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [19]:
print("Credits:",credits.shape)
print("Movies Dataframe:",movies.shape)

Credits: (4803, 4)
Movies Dataframe: (4803, 20)

In [20]:
credits_column_renamed = credits.rename(index=str, columns={"movie_id": "id"})
movies_merge = movies.merge(credits_column_renamed, on='id') #MERGING THE TWO DATASETS BASED ON ONE COMMON COLUMN THAT IS MOVIE_ID
movies_merge.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies_cleaned = movies_merge.drop(columns=['homepage', 'title_x', 'title_y', 'status','production_countries'])
#print(movies_cleaned.head())
#print(movies_cleaned.info())
print(movies_cleaned.head(1)['overview'])

# Drop rows with NaN in 'overview' column
movies_cleaned = movies_cleaned.dropna(subset=['overview'])

0    In the 22nd century, a paraplegic Marine is di...
Name: overview, dtype: object

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfv = TfidfVectorizer(min_df=3,  max_features=None,
            strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
            ngram_range=(1, 3),
            stop_words = 'english')  #Converts a collection of raw documents to a matrix of TF-IDF features.

In [107]:
# Fitting the TF-IDF on the 'overview' text
tfv_matrix = tfv.fit_transform(movies_cleaned['original_title'])
print(tfv_matrix)
print(tfv_matrix.shape)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5379 stored elements and shape (4800, 862)>
  Coords	Values
  (1, 592)	0.40031949121861765
  (1, 114)	0.4257552225208757
  (1, 848)	0.332522265262715
  (1, 659)	0.23182177357836445
  (1, 221)	0.3628076416485741
  (1, 593)	0.4257552225208757
  (1, 849)	0.4257552225208757
  (3, 162)	0.5116479734559036
  (3, 425)	0.5746883182975172
  (3, 163)	0.6387093925024421
  (4, 400)	0.6747843954611052
  (4, 117)	0.7380149183059858
  (5, 719)	0.5569728470856677
  (5, 493)	0.38746020472187376
  (5, 11)	0.4525908116725253
  (5, 720)	0.5786340765594209
  (7, 26)	1.0
  (8, 328)	0.39351685071507636
  (8, 602)	0.4163379059390847
  (8, 319)	0.44279142453787845
  (8, 79)	0.3647657213658838
  (8, 608)	0.40377857295188113
  (8, 329)	0.4238535397736242
  (9, 60)	0.4958622403358247
  (9, 800)	0.5234821103359709
  :	:
  (4762, 187)	1.0
  (4764, 188)	0.6724947209882273
  (4764, 655)	0.7401019188212974
  (4765, 291)	1.0
  (4766, 659)	0.3292149404135897
  (4766, 444)	0.5105714416936481
  (4766, 314)	0.5440275194913695
  (4766, 295)	0.5787645324062404
  (4768, 432)	1.0
  (4771, 591)	1.0
  (4772, 278)	0.429013503694779
  (4772, 317)	0.9032980757466108
  (4773, 511)	0.613339656406184
  (4773, 145)	0.7898192615273093
  (4777, 418)	1.0
  (4782, 737)	0.7223859932178818
  (4782, 464)	0.6914900410003129
  (4784, 188)	1.0
  (4785, 591)	1.0
  (4788, 493)	0.5473943594607463
  (4788, 776)	0.8368747906530338
  (4792, 58)	1.0
  (4795, 215)	1.0
  (4798, 691)	1.0
  (4799, 166)	1.0
(4800, 862)

In [108]:
from sklearn.metrics.pairwise import sigmoid_kernel

# Compute the sigmoid kernel
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)  #calculates the pairwise similarity between movie overviews using a sigmoid kernel
print(sig[0])  #This shows how similar the first movie is to all other movies in the dataset (including itself)

[0.76159416 0.76159416 0.76159416 ... 0.76159416 0.76159416 0.76159416]

In [109]:
# Reverse mapping of indices and movie titles
indices = pd.Series(movies_cleaned.index, index=movies_cleaned['original_title']).drop_duplicates()
#print(indices)
#print(indices['Newlyweds'])
#print(sig[4799])
#print(list(enumerate(sig[indices['Newlyweds']])))
#print(sorted(list(enumerate(sig[indices['Newlyweds']])), key=lambda x: x[1], reverse=True))

In [110]:
def give_recomendations(title, sig=sig):
    # Get the index corresponding to original_title
    idx = indices[title]

    # Get the pairwsie similarity scores
    sig_scores = list(enumerate(sig[idx]))

    # Sort the movies
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)

    # Scores of the 10 most similar movies
    sig_scores = sig_scores[1:11]

    # Movie indices
    movie_indices = [i[0] for i in sig_scores]

    # Top 10 most similar movies
    return movies_cleaned['original_title'].iloc[movie_indices], sig_scores

In [111]:
print(give_recomendations('Avatar'))

(1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
5                                 Spider-Man 3
6                                      Tangled
7                      Avengers: Age of Ultron
8       Harry Potter and the Half-Blood Prince
9           Batman v Superman: Dawn of Justice
10                            Superman Returns
Name: original_title, dtype: object, [(1, 0.7615941559557649), (2, 0.7615941559557649), (3, 0.7615941559557649), (4, 0.7615941559557649), (5, 0.7615941559557649), (6, 0.7615941559557649), (7, 0.7615941559557649), (8, 0.7615941559557649), (9, 0.7615941559557649), (10, 0.7615941559557649)])

In [112]:
import pickle

In [113]:
pickle.dump(movies_cleaned, open('movies.pkl', 'wb'))

In [114]:
movies_cleaned.drop(columns=['budget',	'keywords'	,'original_language',	'popularity',	'production_companies',	'release_date',	'revenue',	'runtime','spoken_languages',	'tagline',	'vote_count', 'cast','vote_average',	'crew'])

,genres,id,original_title,overview
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,[],126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,"[{""id"": 99, ""name"": ""Documentary""}]",25975,My Date with Drew,Ever since the second grade when he first saw ...

In [115]:
pickle.dump(movies_cleaned.to_dict(), open('movie_dict.pkl', 'wb')) #sending the dictionary to streamlit

In [116]:
# Save it
pickle.dump(sig, open('similarity.pkl', 'wb'))

In [117]:
movies_cleaned['genres'].head(1)

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [119]:
def recommend(title, min_similarity=0.5, sig=sig):
    # Get the index corresponding to original_title
    idx = movies[movies['original_title'] == title].index[0]

    # Get the pairwsie similarity scores
    sig_scores = list(enumerate(sig[idx]))

    # Sort the movies
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)

    # Scores of the 10 most similar movies
    sig_scores = [i for i in sig_scores if i[1] > min_similarity][1:21]

    # Movie indices
    #movie_indices = [i[0] for i in sig_scores]

    # Get recommendations with posters
    recommendations = []
    #posters = []
        # Get the genre data
    target_genre = movies[movies['original_title'] == title]['genres'].iloc[0]

    # If it's stored as a string (not list), convert it first:
    if isinstance(target_genre, str):
        target_genre = ast.literal_eval(target_genre)

    # Extract the genre names
    target_genre_names = [genre['name'] for genre in target_genre]
    
    print("target",target_genre_names)
    for i, scores in sig_scores: #skip self
        if scores > min_similarity:
            movie_id = movies.iloc[i]['id']  # Assuming your DataFrame has TMDB IDs
            #poster = fetch_movie_poster(movie_id)

            movie_data = movies.iloc[i]['genres']
            if isinstance(movie_data, str):
                movie_data = ast.literal_eval(movie_data)
            genre_names = [genre['name'] for genre in movie_data]
            #print(genre_names)
            target_genres_set = set(target_genre_names)
            movie_genres_set = set(genre_names)
            common_genres = target_genres_set & movie_genres_set #checking common genres
            if len(common_genres) >= 2:
                recommendations.append(movies.iloc[i]['original_title'])
                #posters.append(poster)
                
    
    return recommendations
recommend("Pirates of the Caribbean: At World's End")

target ['Adventure', 'Fantasy', 'Action']

['Pirates of the Caribbean: On Stranger Tides',
 "Pirates of the Caribbean: Dead Man's Chest",
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The World Is Not Enough',
 'Spice World',
 'End of Days']

In [106]:
movie_title = "Avatar"  # or any other title
genres = movies[movies['original_title'] == movie_title]['genres'].iloc[0]
print(genres)

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]

In [49]:
import ast  # Only needed if the genre data is stored as a string

movie_title = "Avatar"

# Get the genre data
genre_data = movies[movies['original_title'] == movie_title]['genres'].iloc[0]

# If it's stored as a string (not list), convert it first:
if isinstance(genre_data, str):
    genre_data = ast.literal_eval(genre_data)

# Extract the genre names
genre_names = [genre['name'] for genre in genre_data]

print(genre_names)

['Action', 'Adventure', 'Fantasy', 'Science Fiction']